name: internal_calculator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  confetti: ^0.8.0  
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo.png

  fonts:
    - family: Arvo
      fonts:
        - asset: fonts/Arvo-Italic.ttf
        - asset: fonts/Arvo-Regular.ttf
          style: italic
